# Generated by Django 4.2.17 on 2025-01-15 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_type",
        ),
        migrations.AddField(
            model_name="message",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="相关商品",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="消息内容"),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="是否已读"),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收者",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送者",
            ),
        ),
    ]
